### ISSUE TITLE
OPIL/PAML relationship

### ISSUE THREAD

**Issue by jakebeal** [Bioprotocols/labop#19]
Our alpha design for OPIL likely needs to change based on what we are building in PAML. Can interfaces be inferred from protocol structure?

**Comment by danbryce** [comment]
I'd say yes.  It might be a bit tricky when you have variables in the protocol because you have to do something like symbolic execution.  However, without a POML-like language to define the mapping between activity inputs and outputs, you would have a pretty loose definition of what the actual inputs and outputs of the protocol would be.  

Lets say your protocol is a single activity A1, and A1 takes input I1 to produce outputs O1 and O2.  In OPIL, you would have to say your inputs are I1 and your outputs are O1 and O2.  However, A1 might be implemented as "if I1 > X then O1 else O2".  If you wanted to better capture the possible outputs of the procedure, it would be "either O1 or O2" or "if I1 > X then O1 else O2", not "O1 and O2".  

While this may not matter that much (I think) if the outputs are conditional, you could also have conditional inputs.  For example, if you have a conditional execution of the form A1, if X then A2 else A3, then you will only execute A2 or A3.  The inputs to A2 and A3 are potentially different and would be similar to the case with the outputs (above).  

Thus, using OPIL (as is) would cause you to union all the inputs and outputs of all execution paths, instead of characterizing the partitions of these that make sense.  This is probably fine to union and require a user to specify values for all inputs whether they are needed or not.  However, it may be a problem if you are trying to determine whether a protocol can be applied.  Its impossible to know if you get what you want if you cannot map the inputs to the outputs.

**Comment by jakebeal** [comment]
More and more, I've been thinking that we're going to end up building an early form of POML as a side effect of doing this type of reasoning.  I've been thinking it will need to have the ability to talk about both "generic" typing (e.g., things that are true of a protocol no matter the specific execution) and simulated execution against specific parameters.

Like inference with programming languages, there should be gradations of strength in statements that we can get to, depending on the level of sophistication in reasoning, and we probably can deploy incrementally. For example, with the O1/O2 example above, a set of increasingly strong conclusions that can be made are:

- O1 and O2 are both potential outputs
- At least one of O1 and O2 will be produced
- Precisely one of O1 and O2 will be produced

For most applications, however, even just the first will be sufficient.

**Comment by danbryce** [comment]
I agree.  Going beyond a bag of input and outputs will require a more complex model (such as POML).  I’d put this off until we have a use case that goes beyond what we have seen before (i.e., deterministic and linear execution).

**Comment by jakebeal** [comment]
I am closing this as obsolete, given that OPIL is not currently being maintained. We can reopen a new issue if we decide to revive OPIL in a LabOP context.
