### ISSUE TITLE
Link ContainerSpec to SampleCollections

### ISSUE THREAD

**Issue by bbartley** [Bioprotocols/labop#198]
When converting LabOP to autoprotocol/opentrons/emerald cloud serializations, it is often necessary to access container metadata for a given `SampleCollection`.  Currently this is done by following object flows upstream until the `ContainerSpec` is found -- there is a not trivial amount of indirection involved.  We could avoid this indirection by directly linking a `SampleCollection` to its `ContainerSpec`.  There are multiple ways we might do this:

1) add a reference attribute `container` to `SampleCollections`
2) make a `ContainerSpec` a child to `SampleCollection`
3) make a `SampleCollection` child to `ContainerSpec` 

There are likely additional ramifications to this change which we would have to explore.

**Comment by jakebeal** [comment]
I don't think that I understand where the problem is here. Every `SampleCollection` is either a `SampleArray` or a `SampleMask`. 

* If you have a `SampleArray`, then it already does option 1 via property `SampleArray.containerType`.
* If you have a `SampleMask`, then you recursively dereference `SampleMask.source` until you get a `SampleArray`. 

This seems like a simple utility function could do this, and I don't think we're going many layers deep on `SampleMask` in any case.

What am I missing?

**Comment by bbartley** [comment]
You all are right, I had just forgotten that the `container_type` property even existed.
